remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [desnesn.github.io]
description: [A blog of desnes' academic and professional adventures]
